
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'io_testing'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'io_testing'

# These configurations specify where dbt should look for different types of files.
# The `model-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

vars:
  raw_data_date: "2026-01-01"

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models
models:
  io_testing:
    +tags: ['io_testing']
    intermediate:
      +tags: ['intermediate']
    marts:
      +materialized: table
      +tags: ['mart']
      store:
        +schema: marts_store
        +tags: ['store']
      sales:
        +schema: marts_sales
        +tags: ['sales']
      customer:
        +schema: marts_customer
        +tags: ['customer']
